spring:
  application:
    name: vote
  output:
    ansi:
      enabled: always

# logging
logging:
  level:
    root: info

# jpa
jpa:
  show-sql: true
  properties:
    hibernate:
      format_sql: true

# database
datasource:
  driver-class-name: org.postgresql.Driver
  url: jdbc:postgresql://aws-0-ap-northeast-2.pooler.supabase.com:6543/postgres
  username: postgres.utiebnnujtpycwrzeipk
  password: SudtyGo123!!

slack:
  token: