spring:
  application:
    name: vote
  output:
    ansi:
      enabled: always

  # database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://aws-0-ap-northeast-2.pooler.supabase.com:6543/postgres
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  # jpa
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# logging
logging:
  level:
    root: info

slack:
  token: ${SLACK_TOKEN}
  client-id: ${SLACK_CLIENT_ID}
  client-secret: ${SLACK_CLIENT_SECRET}
  redirect-url: ${SLACK_REDIRECT_URL}

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html