spring:
  application:
    name: vote
  output:
    ansi:
      enabled: always

# logging
logging:
  level:
    root: info

# jpa
jpa:
  show-sql: true
  properties:
    hibernate:
      format_sql: true

# database
datasource:


slack:
  token: